# Generated by Django 5.0.1 on 2024-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('cantidad_goles', models.IntegerField()),
                ('cantidad_partidos', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
