# Generated by Django 5.0.1 on 2024-01-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'verbose_name_plural': 'Equipos'},
        ),
    ]
