# Generated by Django 5.0.1 on 2024-02-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_equipos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='noticias')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
