# Generated by Django 5.0.1 on 2024-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_partido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={},
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(choices=[('Por Debutar', 'Por Debutar'), ('Ganado Local', 'Ganado Local'), ('Ganado Visitante', 'Ganado Visitante'), ('Empate', 'Empate')], default='Por Debutar', max_length=20),
        ),
    ]
