# Generated by Django 5.0.1 on 2024-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_partido_options_partido_resultado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='cantidad_goles',
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(choices=[('Por Debutar', 'Por Debutar'), ('Equipo Ganador Local', 'Equipo Ganador Local'), ('Equipo Ganador Visitante', 'Equipo Ganador Visitante'), ('Empate', 'Empate')], default='Por Debutar', max_length=30),
        ),
    ]
