# Generated by Django 5.0.1 on 2024-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_equipos_goles_a_favor_equipos_goles_en_contra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='diferencia_goles',
            field=models.IntegerField(null=True),
        ),
    ]
