# Generated by Django 5.0.1 on 2024-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_equipos_diferencia_goles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='diferencia_goles',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
