# Generated by Django 5.0.1 on 2024-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_equipos_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fechas',
            field=models.CharField(default='Semana', max_length=10),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(max_length=10),
        ),
    ]
