# Generated by Django 5.0.1 on 2024-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_partido_fechas_alter_partido_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fechas',
            field=models.CharField(default='Fecha', max_length=10),
        ),
    ]
