# Generated by Django 5.0.1 on 2024-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_partido_fechas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerceraA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('cantidad_partidos', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('goles_a_favor', models.IntegerField(default=0)),
                ('goles_en_contra', models.IntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
            ],
        ),
    ]
