# Generated by Django 5.0.1 on 2024-03-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centro',
            options={'verbose_name_plural': 'Tabla zona centro'},
        ),
        migrations.AlterModelOptions(
            name='norte',
            options={'verbose_name_plural': 'Tabla zona centro'},
        ),
        migrations.AlterModelOptions(
            name='sur',
            options={'verbose_name_plural': 'Tabla zona sur'},
        ),
        migrations.AlterModelOptions(
            name='terceraa',
            options={'verbose_name_plural': 'Tabla Tercera A'},
        ),
    ]
