# Generated by Django 5.0.1 on 2024-03-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_centro_options_alter_norte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norte',
            options={'verbose_name_plural': 'Tabla zona norte'},
        ),
    ]
