# Generated by Django 5.0.1 on 2024-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_norte_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='norte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='sur',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='terceraa',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
