# Generated by Django 5.0.1 on 2024-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_centro_imagen_norte_imagen_sur_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'verbose_name_plural': 'Calendario Partidos'},
        ),
        migrations.AddField(
            model_name='partido',
            name='zona',
            field=models.CharField(choices=[('Tercera A', 'Tercera A'), ('Norte', 'Zona Norte'), ('Centro', 'Zona Centro'), ('Sur', 'Zona Sur')], default='Escoger', max_length=20),
        ),
    ]
