# Generated by Django 5.0.1 on 2024-03-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_partido_options_partido_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('partido_equipo_local', models.CharField(max_length=30)),
                ('partido_equipo_visitante', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Partidos Programados',
            },
        ),
    ]
