# Generated by Django 5.0.1 on 2024-03-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_programado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programado',
        ),
    ]
