# Generated by Django 5.0.1 on 2024-03-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_programado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_programados_local', to='app.equipos')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_programados_visitante', to='app.equipos')),
            ],
            options={
                'verbose_name': 'Partido Programado',
            },
        ),
    ]
